/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  motorSidebar: [
    {
      type: 'autogenerated',
      dirName: 'motor-sdk', // '.' means the current docs folder
    },
  ],

  // But you can create a sidebar manually
  highwaySidebar: [
    'what-is-sonr',
    'getting-started',
    {
      type: 'category',
      label: 'Modules',
      collapsed: false,
      items: ['modules/buckets', 'modules/objects', 'modules/registry', 'modules/schemas'],
    },
  ],

};

module.exports = sidebars;
