import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the <a href="https://nextjs.org">Sonr Docs!</a>
        </h1>

        <p className={styles.description}>
          The Universal SDK is a set of libraries and tools that allow
          developers to easily interact with Sonr&pos;s blockchain.
        </p>

        <div className={styles.grid}>
          <a href="/build" className={styles.card}>
            <h2>Build &rarr;</h2>
            <p>
              Build user-centric, and privacy preserving App&pos;s with the
              Highway stack.
            </p>
          </a>

          <a href="/design" className={styles.card}>
            <h2>Design &rarr;</h2>
            <p>
              Incorporate the Nebula Design System for a seamless user
              experience!
            </p>
          </a>

          <a href="/integrate" className={styles.card}>
            <h2>Integrate &rarr;</h2>
            <p>
              Use your Highway powered application on Swift, React Native,
              Flutter and more!
            </p>
          </a>

          <a href="/architecture" className={styles.card}>
            <h2>Reference &rarr;</h2>
            <p>
              In depth technical documentation about the Sonr Blockchain
              modules.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </div>
  );
};

export default Home;
